import type {
  GenerateRequest,
  GenerateResult,
  LlmProvider,
  SuggestArtifactMetadataRequest,
  SuggestArtifactMetadataResult
} from '../types';
import { buildFallbackArtifactMetadata } from './metadata';

function escapeText(value: string) {
  return value.replaceAll('\\', '\\\\').replaceAll('`', '\\`');
}

function pickPalette(appId: string) {
  const presets = {
    notes: ['#0f172a', '#1e293b', '#f8fafc'],
    browser: ['#0f172a', '#1d4ed8', '#e0f2fe'],
    files: ['#111827', '#374151', '#f9fafb']
  } as const;
  return presets[appId as keyof typeof presets] ?? ['#0f172a', '#6d28d9', '#f5f3ff'];
}

function buildMockSource(request: GenerateRequest) {
  const summary = escapeText(
    request.instruction
      ? `Last instruction: ${request.instruction}`
      : request.reason === 'initial'
        ? 'Initial render generated by mock provider.'
        : 'No additional instruction provided.'
  );
  const [background, accent, text] = pickPalette(request.appId);
  return `
import { useMemo, useState } from 'react';

type HostBridge = {
  sessionId: string;
  windowId: string;
  appId: string;
  openApp: (appId: string) => Promise<void>;
  readFile: (path: string) => Promise<string>;
  writeFile: (path: string, content: string) => Promise<void>;
  requestUpdate: (instruction: string) => Promise<void>;
};

type WindowProps = {
  host: HostBridge;
  windowState: {
    title: string;
    revision: number;
  };
};

export default function WindowApp({ host, windowState }: WindowProps) {
  const [draft, setDraft] = useState('Try typing here and ask this window to evolve.');
  const greeting = useMemo(
    () => 'Session ' + host.sessionId.slice(0, 8) + ' • Window ' + host.windowId.slice(0, 8),
    [host.sessionId, host.windowId]
  );

  async function saveDraft() {
    await host.writeFile('/notes/' + host.windowId + '.txt', draft);
  }

  return (
    <div style={{ background: '${background}', color: '${text}', borderRadius: 12, padding: 16, height: '100%' }}>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8 }}>
        <strong>{windowState.title}</strong>
        <span style={{ fontSize: 12, opacity: 0.85 }}>rev {windowState.revision}</span>
      </header>
      <p style={{ margin: '8px 0', fontSize: 13, opacity: 0.9 }}>{greeting}</p>
      <p style={{ margin: '8px 0', fontSize: 12, opacity: 0.8 }}>${summary}</p>
      <textarea
        value={draft}
        onChange={(event) => setDraft(event.target.value)}
        style={{
          width: '100%',
          height: 140,
          resize: 'vertical',
          borderRadius: 8,
          border: '1px solid ${accent}',
          padding: 10,
          background: 'rgba(2,6,23,0.45)',
          color: '${text}'
        }}
      />
      <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
        <button
          onClick={saveDraft}
          style={{
            border: 0,
            padding: '7px 12px',
            borderRadius: 8,
            background: '${accent}',
            color: '${text}',
            cursor: 'pointer'
          }}
        >
          Save to Host FS
        </button>
        <button
          onClick={() => host.requestUpdate('Refine this app with richer visuals and interactivity')}
          style={{
            border: '1px solid ${accent}',
            padding: '7px 12px',
            borderRadius: 8,
            background: 'transparent',
            color: '${text}',
            cursor: 'pointer'
          }}
        >
          Ask LLM to Evolve
        </button>
      </div>
    </div>
  );
}
`.trim();
}

export class MockLlmProvider implements LlmProvider {
  async generate(request: GenerateRequest): Promise<GenerateResult> {
    return {
      source: buildMockSource(request),
      backend: 'mock'
    };
  }

  async suggestArtifactMetadata(
    request: SuggestArtifactMetadataRequest
  ): Promise<SuggestArtifactMetadataResult> {
    return {
      ...buildFallbackArtifactMetadata(request),
      backend: 'mock'
    };
  }
}
